// Master store/door list for the quiz intake dropdown and colleague signup.
// Sourced from Mike's monday.com "aBSP Doors" board (Covered Doors group),
// filtered to doors with an assigned Product Educator, covering Mike + 14
// colleagues nationally. Soccer-specialty doors (Teresita Pelayo's and Edward
// Yeboah-Alexander's territories) were excluded as out of scope for a running
// shoe quiz -- flag Mike if that should change.
const STORE_LOCATIONS = [
  "A Runner's Mind - Burlingame",
  "A Runner's Mind - San Francisco",
  "A Snails Pace - Brea",
  "A Snails Pace - Chino Hills",
  "A Snails Pace - Fountain Valley",
  "A Snails Pace - Mission Viejo",
  "A Snails Pace - Monrovia",
  "Athletic Annex - Carmel",
  "Athletic Annex - Fishers",
  "Athletic Annex - Indianapolis",
  "Athletic Performance - Los Gatos",
  "Athletic Treads",
  "Blue Sky Endurance - Coleman Blvd",
  "Blue Sky Endurance - Park Ave",
  "Brazos Running Company",
  "Brooklyn Running Company - Bergen Street",
  "Brooklyn Running Company - Grand Street",
  "Bull City Running Company - W North Carolina",
  "Bull City Running Company - Washington St",
  "Charlotte Running Company - Dilworth",
  "Charlotte Running Company - Lake Norman",
  "Charlotte Running Company - Riverwalk",
  "Charlotte Running Company - South Charlotte (Promenade)",
  "Charm City Run - Annapolis",
  "Charm City Run - Rehoboth Beach",
  "Charm City Run - Timonium",
  "Coastal Run Co. - Easton",
  "Coastal Run Co. - Scarborough",
  "Columbus Running Co - Columbus",
  "Columbus Running Co - Dublin",
  "Columbus Running Co - Grove City",
  "Columbus Running Co - Pickerington",
  "Columbus Running Co - Powell",
  "Columbus Running Co - Westerville",
  "Commonwealth Run Co - Evanston",
  "Confluence Running Company - Corning",
  "Confluence Running Company - Johnson City",
  "Confluence Running Company - Middletown",
  "Confluence Running Company - Watertown",
  "CT Run Co - Brookfield Running",
  "CT Run Co - Darien Running",
  "CT Run Co - Ridgefield",
  "Falls Road Running",
  "Fit2Run - Altamonte",
  "Fit2Run - Coconut Point Estero",
  "Fit2Run - Disney Springs",
  "Fit2Run - Gardens Mall",
  "Fit2Run - New Millenia",
  "Fit2Run - St. Pete",
  "Fit2Run - Tampa International",
  "Fit2Run - UTC",
  "Fleet Feet - 3rd Ave",
  "Fleet Feet - Albany",
  "Fleet Feet - Austin Gateway",
  "Fleet Feet - Blue Ash",
  "Fleet Feet - Boulder",
  "Fleet Feet - Brentwood",
  "Fleet Feet - Bronxville",
  "Fleet Feet - Brooklyn",
  "Fleet Feet - Burbank",
  "Fleet Feet - Canton",
  "Fleet Feet - Carmel",
  "Fleet Feet - Carnes Crossroads",
  "Fleet Feet - Circle C",
  "Fleet Feet - Clemmons",
  "Fleet Feet - Columbia",
  "Fleet Feet - Coppell",
  "Fleet Feet - Dallas",
  "Fleet Feet - Davis",
  "Fleet Feet - Decatur",
  "Fleet Feet - Denver",
  "Fleet Feet - Des Moines (IA)",
  "Fleet Feet - Elk Grove",
  "Fleet Feet - Encino",
  "Fleet Feet - Fifty West",
  "Fleet Feet - Fishers",
  "Fleet Feet - Folsom",
  "Fleet Feet - Fort Myers",
  "Fleet Feet - Fort Worth",
  "Fleet Feet - Fresno",
  "Fleet Feet - Frisco",
  "Fleet Feet - Glastonbury",
  "Fleet Feet - Glendale",
  "Fleet Feet - Greenwood",
  "Fleet Feet - Harrisburg",
  "Fleet Feet - Huntsville",
  "Fleet Feet - Indianapolis",
  "Fleet Feet - Kansas City",
  "Fleet Feet - Lakeview",
  "Fleet Feet - LDB Endurance - Lincoln",
  "Fleet Feet - LDB Endurance - Mercy Road",
  "Fleet Feet - LDB Endurance - Wright St.",
  "Fleet Feet - Long Beach",
  "Fleet Feet - Loveland",
  "Fleet Feet - Madison",
  "Fleet Feet - Mckinney",
  "Fleet Feet - Mechanicsburg",
  "Fleet Feet - Miami",
  "Fleet Feet - Midlothian",
  "Fleet Feet - Montclair",
  "Fleet Feet - Morristown",
  "Fleet Feet - Mount Pleasant",
  "Fleet Feet - Naples",
  "Fleet Feet - New York (Columbus Circle)",
  "Fleet Feet - Newport",
  "Fleet Feet - North Miami",
  "Fleet Feet - Oakley",
  "Fleet Feet - Overland Park",
  "Fleet Feet - Peachtree City",
  "Fleet Feet - Pittsburgh",
  "Fleet Feet - Plano",
  "Fleet Feet - Port St. Lucie",
  "Fleet Feet - Preston Rd.",
  "Fleet Feet - Princeton",
  "Fleet Feet - Queen Creek",
  "Fleet Feet - Richardson",
  "Fleet Feet - Ridgewood",
  "Fleet Feet - Roanoke",
  "Fleet Feet - Roseville",
  "Fleet Feet - Sacramento",
  "Fleet Feet - San Antonio The Quarry",
  "Fleet Feet - San Diego",
  "Fleet Feet - Seaholm",
  "Fleet Feet - Short Pump",
  "Fleet Feet - Springfield",
  "Fleet Feet - Stone Oak",
  "Fleet Feet - Stuart",
  "Fleet Feet - Summerville",
  "Fleet Feet - Summit",
  "Fleet Feet - The Forum",
  "Fleet Feet - The Rim",
  "Fleet Feet - Tuxedo Plaza",
  "Fleet Feet - West 14th",
  "Fleet Feet - West 72nd",
  "Fleet Feet - West Ashley",
  "Fleet Feet - West Chester",
  "Fleet Feet - West Hartford",
  "Fleet Feet - Westfield",
  "Fleet Feet - Westhampton",
  "Fleet Feet - Westport",
  "Fleet Feet - Winston-Salem",
  "Fleet Feet - York",
  "Fleet Feet Chicago - Lincoln Square",
  "Fleet Feet Chicago - Oldtown",
  "Fleet Feet Chicago - Southloop",
  "Fleet Feet Cleveland - Northfield",
  "Fleet Feet Cleveland - Pepper Pike",
  "Fleet Feet Cleveland - Strongsville",
  "Fleet Feet Cleveland - Westlake",
  "Fleet Feet Cleveland - Youngstown",
  "Fleet Feet Columbus - Lewis Center",
  "Fleet Feet Columbus - N. Hamilton",
  "Fleet Feet Columbus - West Lane Ave",
  "Fleet Feet Houston - Greenbriar",
  "Fleet Feet Houston - Katy",
  "Fleet Feet Houston - River Oaks",
  "Fleet Feet Houston - Sugar Land",
  "Fleet Feet Houston - The Woodlands",
  "Fleet Feet Houston - Vintage Park",
  "Fleet Feet Houston - Woodway",
  "Fleet Feet Mcallen - Brownsville",
  "Fleet Feet Mcallen - McAllen",
  "Fleet Feet Nashville - Brentwood",
  "Fleet Feet Nashville - Cool Springs",
  "Fleet Feet Nashville - Green Hills",
  "Fleet Feet Nashville - Hendersonville",
  "Fleet Feet Nashville - Mt. Juliet",
  "Fleet Feet Nashville - Murfeesboro",
  "Fleet Feet Raleigh - Colonnade Center",
  "Fleet Feet Raleigh - Morrisville",
  "Fleet Feet Raleigh - Wade Ave.",
  "Fleet Feet Raleigh - Woodburn Rd",
  "Fleet Feet Rochester - Buffalo",
  "Fleet Feet Rochester - Rochester",
  "Fleet Feet Rochester - Victor",
  "Fleet Feet Sports - 9th St",
  "Fleet Feet Sports - Bardstown Rd",
  "Fleet Feet Sports - Breckenridge Ln",
  "Fleet Feet Sports - Carrboro",
  "Fleet Feet Sports - E Liberty Ave.",
  "Fleet Feet Sports - Fayetteville Rd",
  "Fleet Feet Sports - Jackson Road",
  "Fleet Feet Sports - Lawrence",
  "Fleet Feet Sports - Longmeadow",
  "Fleet Feet Sports - Myers Park",
  "Fleet Feet Sports - Northville",
  "Fleet Feet Sports - Pittsburgh",
  "Fleet Feet Sports - Topeka",
  "Fleet Feet Sports - W Loop",
  "Fleet Feet Sports - Waverly Walk",
  "Fleet Feet Sports - West Lafayette",
  "Fleet Feet Toledo - Toledo",
  "Foot Tech - 122nd Street",
  "Foot Tech - 19th Street",
  "Footprint USA - Colma",
  "Footprint USA - San Francisco",
  "FrontRunners - Brentwood",
  "FrontRunners - Torrance",
  "Fusion Footwear Corp. - Oshkosh",
  "Game Changers Running Company - Amelia Island",
  "Game Changers Running Company - Richmond Hill",
  "Game Changers Running Company - St. Simons Island",
  "Gazelle Sports - 28th St",
  "Gazelle Sports - Birmingham",
  "Gazelle Sports - Holland",
  "Gazelle Sports - Kalamazoo",
  "Gazelle Sports - Monroe Center",
  "Gazelle Sports - Northville",
  "Go Run Miami",
  "Gold Country Run + Sport - El Dorado Hills",
  "Gold Country Run + Sport - Rocklin",
  "Heartbreak Hill Running Company - Boston",
  "Heartbreak Hill Running Company - Cambridge",
  "Heartbreak Hill Running Company - Chicago",
  "Heartbreak Hill Running Company - Newton",
  "Heartbreak Hill Running Company - Santa Monica",
  "Holabird Sports - Baltimore",
  "iRun - Miami",
  "John's Run & Walk - Lexington",
  "Jus Running Inc - Asheville",
  "Lake Placid Running and Triathlon Company",
  "LSD - Los Angeles",
  "Luke's Locker - Dallas",
  "Luke's Locker - Fort Worth",
  "Marathon Sports - Andover",
  "Marathon Sports - Arlington",
  "Marathon Sports - Boston",
  "Marathon Sports - Branford",
  "Marathon Sports - Brookline",
  "Marathon Sports - Brunswick",
  "Marathon Sports - Cambridge",
  "Marathon Sports - Concord",
  "Marathon Sports - Fairfield",
  "Marathon Sports - Lexington",
  "Marathon Sports - Manchester",
  "Marathon Sports - Mansfield",
  "Marathon Sports - Melrose",
  "Marathon Sports - Montpelier",
  "Marathon Sports - Newburyport",
  "Marathon Sports - Northampton",
  "Marathon Sports - Norwell",
  "Marathon Sports - Old Saybrook",
  "Marathon Sports - Plymouth",
  "Marathon Sports - Portland",
  "Marathon Sports - Portsmouth",
  "Marathon Sports - Providence",
  "Marathon Sports - Reading",
  "Marathon Sports - Shrewsbury",
  "Marathon Sports - South Yarmouth",
  "Marathon Sports - Swampscott",
  "Marathon Sports - Wellesley Hills",
  "Marathon Sports - Westford",
  "Milestone Running - Cajon Blvd",
  "Milestone Running - Garnet",
  "Mill City Running - Minneapolis",
  "Minnesota Treads - Rochester",
  "Naperville Run Company - Naperville",
  "OK Runner - Norman",
  "OK Runner - Oklahoma City",
  "Pace Yourself Run Co - Holly Springs",
  "Pace Yourself Run Co - Southern Pines",
  "Pace Yourself Run Co - Wendell",
  "Pacers - 14th St",
  "Pacers - Alexandria",
  "Pacers - Clarendon",
  "Pacers - Georgetown",
  "Pacers - Navy Yard",
  "Performance Footwear - Las Vegas",
  "Performance Footwear - Tuscon",
  "Performance Running Outfitters - Brookfield",
  "Performance Running Outfitters - Third Ward",
  "Potomac River Running - Arlington",
  "PR Run & Walk - Midlothian",
  "PR Run & Walk - Reston",
  "Pulse ATX - Austin",
  "Red Rock Running Co. - Centennial Hills",
  "Red Rock Running Co. - Deer Springs",
  "Red Rock Running Co. - Henderson",
  "Red Rock Running Co. - Southwest",
  "Reign Running",
  "Renegade - Los Angeles",
  "Renegade Running - Oakland",
  "Reno Running Company - Lakeside",
  "Reno Running Company - Sparks",
  "Reno Running Company - Summit",
  "Road Runner Sports - Arlington",
  "Road Runner Sports - Atlanta",
  "Road Runner Sports - Bellevue",
  "Road Runner Sports - Berkeley",
  "Road Runner Sports - Calabasas",
  "Road Runner Sports - Campbell",
  "Road Runner Sports - Carlsbad",
  "Road Runner Sports - Chandler",
  "Road Runner Sports - Cherry Hill",
  "Road Runner Sports - Chula Vista",
  "Road Runner Sports - Columbia",
  "Road Runner Sports - Concord",
  "Road Runner Sports - Costa Mesa",
  "Road Runner Sports - Downers Grove",
  "Road Runner Sports - Falls Church",
  "Road Runner Sports - Hilliard",
  "Road Runner Sports - Kent",
  "Road Runner Sports - Kildeer",
  "Road Runner Sports - King of Prussia",
  "Road Runner Sports - Laguna Hills",
  "Road Runner Sports - Lakewood",
  "Road Runner Sports - Manhattan Beach",
  "Road Runner Sports - Marietta",
  "Road Runner Sports - Naperville",
  "Road Runner Sports - North Brunswick",
  "Road Runner Sports - Oxnard",
  "Road Runner Sports - Paramus",
  "Road Runner Sports - Peachtree Corners",
  "Road Runner Sports - Portland",
  "Road Runner Sports - Rockville",
  "Road Runner Sports - San Carlos",
  "Road Runner Sports - San Diego",
  "Road Runner Sports - Santa Monica",
  "Road Runner Sports - Scottsdale",
  "Road Runner Sports - Seattle",
  "Road Runner Sports - Shrewsbury",
  "Road Runner Sports - Solana Beach",
  "Road Runner Sports - South Denver",
  "Road Runner Sports - Sterling",
  "Road Runner Sports - Studio City",
  "Road Runner Sports - Sunnyvale",
  "Road Runner Sports - Temecula",
  "Road Runner Sports - Tempe",
  "Road Runner Sports - Thousand Oaks",
  "Road Runner Sports - Torrance",
  "Road Runner Sports - Tualatin",
  "Road Runner Sports - Tucson",
  "Road Runner Sports - Tustin",
  "Road Runner Sports - Uptown Phoenix",
  "Road Runner Sports - Westminster",
  "Road Runner Sports - Wilmette",
  "Road Runner Sports - Worthington (Columbus)",
  "Run Flagstaff",
  "Run In - Anderson",
  "Run In - Greenville",
  "Run In - Simpsonville",
  "Run With Us",
  "Runner's Den",
  "Runner's Depot - Davie",
  "Runner's Depot - Ft. Lauderdale",
  "Runner's Depot - Sunrise",
  "Runner's Depot - The Abbey",
  "Runners Plus - Fairborn",
  "Runners Plus - South Dayton",
  "Runners Republic - Glenview",
  "Running Warehouse - Alpharetta",
  "Running Warehouse - Dunwoody",
  "Running Warehouse - San Luis Obispo",
  "RunningLane - Huntsville",
  "Sacramento Running Company",
  "Sayville Running Company - Sayville",
  "Sayville Running Company - Smithtown",
  "Second Sole - Akron",
  "Second Sole - Canton",
  "Second Sole - Gahanna",
  "Second Sole - Lyndhurst",
  "Second Sole - Massillon",
  "Second Sole - Medina",
  "Second Sole - Toledo",
  "Second Sole - Wooster",
  "Second Sole - Youngstown",
  "Sole Sports - Arcadia",
  "Sole Sports - Gilbert",
  "Sole Sports - Scottsdale",
  "Sole Sports - Tempe",
  "Super Runners - 50th St Midtown",
  "Super Runners - 79th St Upper West Side",
  "Super Runners - 7th Ave Midtown",
  "Super Runners - 82nd St Upper East Side",
  "The Exchange - Nashville",
  "The Outpost Running & Walking Co.",
  "The Running Elements - Daytona",
  "Tri-State Running Co - Edgewood",
  "Twin City Running - Burnsville",
  "Twin City Running - Eden Prairie",
  "Twin City Running - Maple Grove",
  "Twin City Running - St. Paul",
  "Twin City Running - Woodbury",
  "Waco Running Company",
  "Weststride - Atlanta",
];
